Repository vuejs/vue-devtools, pull requests merged in 2018-07, with the labels that each got.

#575 SharedData: classifyComponent, openInEditorHost
  docs/open-in-editor.md
  shells/dev/target/index.js
  src/backend/config.js
  src/backend/highlighter.js
  src/backend/index.js
  src/devtools/index.js
  src/devtools/views/components/ComponentInspector.vue
  src/devtools/views/components/ComponentInstance.vue
  src/devtools/views/components/ComponentTree.vue
  src/devtools/views/components/module.js
  src/devtools/views/events/EventsHistory.vue
  src/devtools/views/events/module.js
  src/shared-data.js
  src/util.js
Labels: enhancement, semver-minor

#621 Don't break when CSP is on in Firefox (#616)
  shells/chrome/src/detector.js
  shells/chrome/src/hook.js
  src/devtools/env.js
Labels: discussion

#661 feat: detect Nuxt.js
  shells/chrome/icons/128.nuxt.png
  shells/chrome/icons/16.nuxt.png
  shells/chrome/icons/48.nuxt.png
  shells/chrome/popups/disabled.nuxt.html
  shells/chrome/popups/enabled.nuxt.html
  shells/chrome/src/background.js
  shells/chrome/src/detector.js
Labels: enhancement, semver-minor

#659 show injected properties
  cypress/integration/components-tab.js
  shells/dev/target/Other.vue
  src/backend/index.js
Labels: new feature, semver-minor

#583 Add dropdown menu to DataField with Copy Value
  src/devtools/components/DataField.vue
  src/devtools/locales/en.js
  src/util.js
Labels: enhancement, new feature, semver-minor, work in progress

#543 High-density mode
  src/devtools/components/DataField.vue
  src/devtools/components/StateInspector.vue
  src/devtools/index.js
  src/devtools/plugins.js
  src/devtools/views/components/ComponentInstance.vue
  src/devtools/views/components/ComponentTree.vue
  src/devtools/views/components/module.js
  src/devtools/views/events/EventsHistory.vue
  src/devtools/views/settings/GlobalPreferences.vue
  src/devtools/views/vuex/VuexHistory.vue
  src/shared-data.js
Labels: enhancement, work in progress
