Repository vuejs/vue-devtools, pull requests merged in 2018-03, with the labels that each got.

#625 (fixes #597) Allow debugging through proxy
  shells/electron/README.md
  shells/electron/index.js
  shells/electron/src/backend.js
  shells/electron/src/devtools.js
Labels: new feature, semver-minor

#599 improve the display of symbols and functions
  shells/dev/target/NativeTypes.vue
  shells/dev/target/store.js
  src/util.js
Labels: enhancement, semver-patch, work in progress

#614 Make ability to send vm to console slightly more obvious
  src/devtools/locales/en.js
  src/devtools/views/components/ComponentInstance.vue
Labels: enhancement, semver-patch

#637 Fix loosing <Root> #269
  src/backend/index.js
Labels: bug, semver-patch
